export const Experts = [
  {
    name: "John Markraw",
    reviews: 8,
    languages: ["English", "Hindi"],
    available: "2023-09-12T10:00:00",
    free: true,
    consultation: 0,
  },
  {
    name: "John Doe",
    reviews: 5,
    languages: ["English", "French", "Spanish"],
    available: "2023-09-13T12:00:00",
    free: true,
    consultation: 0,
  },
  {
    name: "Jane Doe",
    reviews: 4,
    languages: ["English", "German", "Italian"],
    available: "2023-09-14T10:00:00",
    free: false,
    consultation: 1500,
  },
  {
    name: "Peter Smith",
    reviews: 3,
    languages: ["English", "Chinese", "Japanese"],
    available: "2023-09-15T14:00:00",
    free: true,
    consultation: 0,
  },
  {
    name: "Susan Jones",
    reviews: 2,
    languages: ["English", "Hindi", "Marathi"],
    available: "2023-09-16T16:00:00",
    free: false,
    consultation: 2500,
  },
  {
    name: "David Williams",
    reviews: 1,
    languages: ["English", "Spanish", "Portuguese"],
    available: "2023-09-17T18:00:00",
    free: true,
    consultation: 0,
  },
  {
    name: "Emily Brown",
    reviews: 5,
    languages: ["English", "Russian", "German"],
    available: "2023-09-18T20:00:00",
    free: true,
    consultation: 0,
  },
  {
    name: "Michael Thomas",
    reviews: 4,
    languages: ["English", "French", "Italian"],
    available: "2023-09-19T22:00:00",
    free: false,
    consultation: 1500,
  },
  {
    name: "Sarah Wilson",
    reviews: 3,
    languages: ["English", "Spanish", "Portuguese"],
    available: "2023-09-20T00:00:00",
    free: true,
    consultation: 0,
  },
  {
    name: "William Johnson",
    reviews: 2,
    languages: ["English", "Chinese", "Japanese"],
    available: "2023-09-21T02:00:00",
    free: false,
    consultation: 2500,
  },
  {
    name: "Elizabeth Green",
    reviews: 1,
    languages: ["English", "Hindi", "Marathi"],
    available: "2023-09-22T04:00:00",
    free: true,
    consultation: 0,
  },
  {
    name: "Thomas Davis",
    reviews: 5,
    languages: ["English", "French", "Spanish"],
    available: "2023-09-23T06:00:00",
    free: true,
    consultation: 0,
  },
  {
    name: "Jennifer White",
    reviews: 4,
    languages: ["English", "German", "Italian"],
    available: "2023-09-24T08:00:00",
    free: false,
    consultation: 1500,
  },
  {
    name: "Charles Black",
    reviews: 3,
    languages: ["English", "Chinese", "Japanese"],
    available: "2023-09-25T10:00:00",
    free: true,
    consultation: 0,
  },
  {
    name: "Maria Brown",
    reviews: 2,
    languages: ["English", "Hindi", "Marathi"],
    available: "2023-09-26T12:00:00",
    free: false,
    consultation: 2500,
  },
  {
    name: "Henry Williams",
    reviews: 1,
    languages: ["English", "Spanish", "Portuguese"],
    available: "2023-09-27T14:00:00",
    free: true,
    consultation: 0,
  },
];
