export const Experts = [
  {
    name: "John Markraw",
    reviews: 8,
    languages: ["English", "Hindi"],
    email: "pranshujain0221@gmail.com",
    available: "2023-09-12T10:00:00",
    free: true,
    consultation: 0,
    about: "I am a seasoned legal expert with a focus on property law.",
    latestCaseType: "Property",
  },
  {
    name: "John Doe",
    reviews: 5,
    languages: ["English", "French", "Spanish"],
    email: "test@gmail.com",
    available: "2023-09-13T12:00:00",
    free: true,
    consultation: 0,
    about:
      "I specialize in immigration law and have helped numerous clients with their visa applications.",
    latestCaseType: "Immigration",
  },
  {
    name: "Jane Doe",
    reviews: 4,
    languages: ["English", "German", "Italian"],
    email: "test@gmail.com",
    available: "2023-09-14T10:00:00",
    free: false,
    consultation: 1500,
    about:
      "I am a family law expert, and I have successfully handled various divorce and child custody cases.",
    latestCaseType: "Family Law",
  },
  {
    name: "Peter Smith",
    reviews: 3,
    languages: ["English", "Chinese", "Japanese"],
    email: "test@gmail.com",
    available: "2023-09-15T14:00:00",
    free: true,
    consultation: 0,
    about:
      "I have extensive experience in corporate law and have worked with major multinational companies.",
    latestCaseType: "Corporate Law",
  },
  {
    name: "Susan Jones",
    reviews: 2,
    languages: ["English", "Hindi", "Marathi"],
    email: "test@gmail.com",
    available: "2023-09-16T16:00:00",
    free: false,
    consultation: 2500,
    about:
      "I specialize in intellectual property law and have helped clients protect their inventions and trademarks.",
    latestCaseType: "Intellectual Property",
  },
  {
    name: "David Williams",
    reviews: 1,
    languages: ["English", "Spanish", "Portuguese"],
    email: "test@gmail.com",
    available: "2023-09-17T18:00:00",
    free: true,
    consultation: 0,
    about:
      "I am a criminal defense attorney with a track record of successfully defending clients in high-profile cases.",
    latestCaseType: "Criminal Defense",
  },
  {
    name: "Emily Brown",
    reviews: 5,
    languages: ["English", "Russian", "German"],
    email: "test@gmail.com",
    available: "2023-09-18T20:00:00",
    free: true,
    consultation: 0,
    about:
      "I specialize in environmental law and have represented clients in cases related to environmental protection.",
    latestCaseType: "Environmental Law",
  },
  {
    name: "Michael Thomas",
    reviews: 4,
    languages: ["English", "French", "Italian"],
    email: "test@gmail.com",
    available: "2023-09-19T22:00:00",
    free: false,
    consultation: 1500,
    about:
      "I am an employment law expert with experience in resolving workplace disputes and labor-related issues.",
    latestCaseType: "Employment Law",
  },
  {
    name: "Sarah Wilson",
    reviews: 3,
    languages: ["English", "Spanish", "Portuguese"],
    email: "test@gmail.com",
    available: "2023-09-20T00:00:00",
    free: true,
    consultation: 0,
    about:
      "I specialize in immigration law and have helped clients with their immigration and naturalization processes.",
    latestCaseType: "Immigration",
  },
  {
    name: "William Johnson",
    reviews: 2,
    languages: ["English", "Chinese", "Japanese"],
    email: "test@gmail.com",
    available: "2023-09-21T02:00:00",
    free: false,
    consultation: 2500,
    about:
      "I am a real estate attorney with experience in property transactions and real estate disputes.",
    latestCaseType: "Real Estate",
  },
  {
    name: "Elizabeth Green",
    reviews: 1,
    languages: ["English", "Hindi", "Marathi"],
    available: "2023-09-22T04:00:00",
    email: "test@gmail.com",
    free: true,
    consultation: 0,
    about:
      "I am a personal injury lawyer and have helped clients recover compensation for their injuries.",
    latestCaseType: "Personal Injury",
  },
  {
    name: "Thomas Davis",
    reviews: 5,
    languages: ["English", "French", "Spanish"],
    email: "test@gmail.com",
    available: "2023-09-23T06:00:00",
    free: true,
    consultation: 0,
    about:
      "I specialize in family law and have handled various divorce and child custody cases successfully.",
    latestCaseType: "Family Law",
  },
  {
    name: "Jennifer White",
    reviews: 4,
    languages: ["English", "German", "Italian"],
    available: "2023-09-24T08:00:00",
    email: "test@gmail.com",
    free: false,
    consultation: 1500,
    about:
      "I am a business law attorney and have assisted clients in various corporate legal matters.",
    latestCaseType: "Business Law",
  },
  {
    name: "Charles Black",
    reviews: 3,
    languages: ["English", "Chinese", "Japanese"],
    email: "test@gmail.com",
    available: "2023-09-25T10:00:00",
    free: true,
    consultation: 0,
    about:
      "I am a patent attorney and have helped clients secure patents for their inventions.",
    latestCaseType: "Patent Law",
  },
  {
    name: "Maria Brown",
    reviews: 2,
    languages: ["English", "Hindi", "Marathi"],
    email: "test@gmail.com",
    available: "2023-09-26T12:00:00",
    free: false,
    consultation: 2500,
    about:
      "I specialize in immigration law and have assisted clients in their immigration journey.",
    latestCaseType: "Immigration",
  },
  {
    name: "Henry Williams",
    reviews: 1,
    languages: ["English", "Spanish", "Portuguese"],
    email: "test@gmail.com",
    available: "2023-09-27T14:00:00",
    free: true,
    consultation: 0,
    about:
      "I am an intellectual property attorney and have helped clients protect their inventions and trademarks.",
    latestCaseType: "Intellectual Property",
  },
];
