import type { Metadata } from "next";
import Footer from "../assets/Footer";
import Navbar from "../assets/Navbar";
import "../globals.css";

export const metadata: Metadata = {
  title: "Legi Companion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <Navbar />
        <div className="bg-white text-black">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
